services:
  - type: web
    name: stake-arena
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn --worker-class eventlet -w 4 --timeout 120 app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: PORT
        value: 10000
    autoDeploy: true
